var namespacecomandos =
[
    [ "ActualizarComercio", "classcomandos_1_1_actualizar_comercio.html", "classcomandos_1_1_actualizar_comercio" ],
    [ "ActualizarInventario", "classcomandos_1_1_actualizar_inventario.html", "classcomandos_1_1_actualizar_inventario" ],
    [ "ActualizarNPCs", "classcomandos_1_1_actualizar_n_p_cs.html", "classcomandos_1_1_actualizar_n_p_cs" ],
    [ "ActualizarPersonaje", "classcomandos_1_1_actualizar_personaje.html", "classcomandos_1_1_actualizar_personaje" ],
    [ "ActualizarPersonajeLvl", "classcomandos_1_1_actualizar_personaje_lvl.html", "classcomandos_1_1_actualizar_personaje_lvl" ],
    [ "ActualizarTrueque", "classcomandos_1_1_actualizar_trueque.html", "classcomandos_1_1_actualizar_trueque" ],
    [ "Atacar", "classcomandos_1_1_atacar.html", "classcomandos_1_1_atacar" ],
    [ "Batalla", "classcomandos_1_1_batalla.html", "classcomandos_1_1_batalla" ],
    [ "BatallaNPC", "classcomandos_1_1_batalla_n_p_c.html", "classcomandos_1_1_batalla_n_p_c" ],
    [ "ComandosCliente", "classcomandos_1_1_comandos_cliente.html", "classcomandos_1_1_comandos_cliente" ],
    [ "ComandosEscucha", "classcomandos_1_1_comandos_escucha.html", "classcomandos_1_1_comandos_escucha" ],
    [ "ComandosServer", "classcomandos_1_1_comandos_server.html", "classcomandos_1_1_comandos_server" ],
    [ "Comercio", "classcomandos_1_1_comercio.html", "classcomandos_1_1_comercio" ],
    [ "Conexion", "classcomandos_1_1_conexion.html", "classcomandos_1_1_conexion" ],
    [ "CrearPersonaje", "classcomandos_1_1_crear_personaje.html", "classcomandos_1_1_crear_personaje" ],
    [ "FinalizarBatalla", "classcomandos_1_1_finalizar_batalla.html", "classcomandos_1_1_finalizar_batalla" ],
    [ "FinalizarBatallaNPC", "classcomandos_1_1_finalizar_batalla_n_p_c.html", "classcomandos_1_1_finalizar_batalla_n_p_c" ],
    [ "InicioSesion", "classcomandos_1_1_inicio_sesion.html", "classcomandos_1_1_inicio_sesion" ],
    [ "InicioSesionSet", "classcomandos_1_1_inicio_sesion_set.html", "classcomandos_1_1_inicio_sesion_set" ],
    [ "MostrarMapas", "classcomandos_1_1_mostrar_mapas.html", "classcomandos_1_1_mostrar_mapas" ],
    [ "Movimiento", "classcomandos_1_1_movimiento.html", "classcomandos_1_1_movimiento" ],
    [ "MovimientoNPC", "classcomandos_1_1_movimiento_n_p_c.html", "classcomandos_1_1_movimiento_n_p_c" ],
    [ "Registro", "classcomandos_1_1_registro.html", "classcomandos_1_1_registro" ],
    [ "RegistroSet", "classcomandos_1_1_registro_set.html", "classcomandos_1_1_registro_set" ],
    [ "Salir", "classcomandos_1_1_salir.html", "classcomandos_1_1_salir" ],
    [ "SalirSet", "classcomandos_1_1_salir_set.html", "classcomandos_1_1_salir_set" ],
    [ "Talk", "classcomandos_1_1_talk.html", "classcomandos_1_1_talk" ],
    [ "Trueque", "classcomandos_1_1_trueque.html", "classcomandos_1_1_trueque" ]
];